apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: kabal-api
  namespace: klage
  labels:
    team: klage
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: kabal-api
        type: POSTGRES_12
        maintenanceWindow:
          day: 1
          hour: 4
        tier: {{ db_tier }}
        diskType: SSD
        highAvailability: {{ db_ha }}
        diskSize: {{ db_size }}
        diskAutoresize: true
        autoBackupTime: "02:00"
        cascadingDelete: false
        databases:
          - name: kabal-api
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
      claims:
        groups:
          - id: {{ROLE_KLAGE_SAKSBEHANDLER}}
          - id: {{ROLE_KLAGE_FAGANSVARLIG}}
          - id: {{ROLE_KLAGE_LEDER}}
          - id: {{ROLE_KLAGE_MERKANTIL}}
          - id: {{ROLE_KLAGE_FORTROLIG}}
          - id: {{ROLE_KLAGE_STRENGT_FORTROLIG}}
          - id: {{ROLE_KLAGE_EGEN_ANSATT}}
          - id: {{ROLE_GOSYS_OPPGAVE_BEHANDLER}}
        extra:
          - NAVident
  elastic:
    instance: oppgave-es
  port: 7081
  liveness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 400m
      memory: 256Mi
  ingresses:
  {{#each ingresses as |ingress|}}
    - {{ingress}}
  {{/each}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/prometheus
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: kabal
        - application: klage-oppgave
        - application: klage-oppgave-consumer
        - application: k9-klage
          namespace: k9saksbehandling
          cluster: {{k9_cluster}}
    outbound:
      rules:
        - application: klage-redis
        - application: clamav
          namespace: clamav
      external:
      {{#each externalHosts as |host|}}
        - host: {{host}}
      {{/each}}
  envFrom:
    - secret: srvklage-saksbeh
    - secret: sts-apikey
    - secret: pdl-apikey
    - secret: oppgave-apikey
    - secret: slack-url
    - secret: slack-channel-id
    - secret: norg2
    - secret: axsys
    - secret: elastic
    - secret: journalpost-apikey
    - secret: ereg
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{springProfile}}
